title: "The Global Zoogeochemistry Network"
title_separator          : "-"
subtitle: "Home"
description: "Zoogeochemistry: Alchemists of the Wild"
url: "https://globalzoogeochemnet.github.io"
teaser: "/assets/images/poster.png"
logo: "/assets/images/favicon.io"
words_per_minute         : 200

theme: jekyll-theme-minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-sitemap
  
# Site Settings
locale                   : "en-US"

# Social Sharing
twitter: 
  username               : 

# Site Footer

# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/