title: "The Global Zoogeochemistry Network"
title_separator : "-"
subtitle: "Home"
description: "Zoogeochemistry: Alchemists of the Wild"
url: "https://globalzoogeochemnet.github.io"
logo: "/assets/images/poster.png"


theme: minimal-mistakes-jekyll

# Site Settings
locale: "en-US"

header:
  nav:
    - text: "Home"
      url: "/"
    - text: "About"
      url: "/about/"
    - text: "Databases"
      url: "/databases/"
    - text: "Courses & Workshops"
      url: "/courses/"
